FROM rust:1.89

# 安装 GUI 依赖
RUN apt update && apt install -y libwebkit2gtk-4.1-dev \
    build-essential \
    curl \
    wget \
    file \
    libgtk-3-dev \
    librsvg2-dev \
    libxdo-dev \
    libssl-dev \
    patchelf

# 安装 Node.js 22
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
  && apt install -y nodejs

# 安装 pnpm 10
RUN npm install -g pnpm@10

# 安装 Protobuf
RUN apt install -y protobuf-compiler

# 安装测试工具
RUN apt install -y bridge-utils

# Rust 配置
RUN rustup set auto-self-update disable \
  && rustup component add rustfmt \
  && rustup component add clippy

# 安装 musl 工具（可选，用于交叉编译）
RUN apt install -y musl-tools libappindicator3-dev llvm clang

# 系统配置（可选，用于测试）
RUN echo "net.bridge.bridge-nf-call-iptables=0" >> /etc/sysctl.conf \
  && echo "net.bridge.bridge-nf-call-ip6tables=0" >> /etc/sysctl.conf

# 安装 code-server 和扩展
RUN curl -fsSL https://code-server.dev/install.sh | sh \
  && code-server --install-extension cnbcool.cnb-welcome \
  && code-server --install-extension redhat.vscode-yaml \
  && code-server --install-extension dbaeumer.vscode-eslint \
  && code-server --install-extension waderyan.gitblame \
  && code-server --install-extension mhutchie.git-graph \
  && code-server --install-extension donjayamanne.githistory \
  && code-server --install-extension tencent-cloud.coding-copilot \
  && echo done
