$:
  vscode:
    - docker:
        build: .idc/dockerfile
      services:
        - vscode
        - docker
      stages:
        - name: ls
          script: ls -al
# 代码扫描流水线配置
# 在 develop 和 main 分支 push 时触发
"(main|develop)":
  push:
    - docker:
        image: rust:1.89
        volumes:
          - /root/.cargo:copy-on-write
          - ./target:copy-on-write
      stages:
        - name: setup protoc
          script: |
            apt-get update
            apt-get install -y protobuf-compiler

        - name: setup tools for test
          script: |
            apt-get install -y bridge-utils sudo libclang-dev

        - name: install node and pnpm
          script: |
            apt-get install -y curl
            curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
            apt-get install -y nodejs
            npm install -g pnpm@10

        - name: install frontend dependencies
          script: |
            pnpm -r install
            pnpm -r --filter "./easytier-web/*" build

        - name: install gui dependencies
          script: |
            bash ./.github/workflows/install_gui_dep.sh
            rustup component add rustfmt
            rustup component add clippy

        - name: check formatting
          allowFailure: true
          script: cargo fmt --all -- --check

        - name: check clippy
          allowFailure: true
          script: |
            mkdir -p easytier-gui/dist
            cargo clippy --all-targets --all-features --all -- -D warnings

        - name: run tests
          allowFailure: true
          script: |
            prlimit --pid $$ --nofile=1048576:1048576
            cargo test --no-default-features --features=full --verbose -- --test-threads=1
